From wgf5544/centos:base-centos6
MAINTAINER gaofeng Wu "gfwu@zshield.net"

USER root

ADD . /install

RUN cd /install/; ./mysql-install.sh; cd ..;rm -rf /install

ENTRYPOINT ["/entrypoint.sh"]

EXPOSE 3306
